import { day1 } from "./day1/index.mjs";
import { day10 } from "./day10/index.mjs";
import { day11 } from "./day11/index.mjs";
import { day12 } from "./day12/index.mjs";
import { day13 } from "./day13/index.mjs";
import { day2 } from "./day2/index.mjs";
import { day3 } from "./day3/index.mjs";
import { day4 } from "./day4/index.mjs";
import { day5 } from "./day5/index.mjs";
import { day6 } from "./day6/index.mjs";
import { day7 } from "./day7/index.mjs";
import { day8 } from "./day8/index.mjs";
import { day9 } from "./day9/index.mjs";

console.time("Run");
// await day1();
// await day2();
// await day3();
// await day4();
// await day5();
// await day6();
// await day7();
// await day8();
// await day9();
// await day10();
// await day11();
await day12();
// await day13();
console.timeEnd("Run");
